/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-1-3 下午10:55' with Gradle 2.11
 *
 * @author Administrator, @date 17-1-3 下午10:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
